CREATE DATABASE bdtelecom;
USE bdtelecom;

CREATE TABLE tbl_servicios (ID_Servicio INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY, ID_Categoria INT(10) NOT NULL, nombre VARCHAR(50) NOT NULL, descripcion VARCHAR(1000) NOT NULL);

CREATE TABLE tbl_galeria (ID_Imagen INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY, ID_Servicio INT(10) NOT NULL, nombre VARCHAR(50) NOT NULL, descripcion VARCHAR(1000) NOT NULL, foto VARCHAR(500) NOT NULL);

CREATE TABLE tbl_cotizacion (ID_Cotizacion INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY, Numero_Cliente INT(20) NOT NULL, ID_Servicio INT(10) NOT NULL);

CREATE TABLE tbl_clientesregistrados (tipo_id VARCHAR(5) NOT NULL, Numero VARCHAR(20) NOT NULL PRIMARY KEY, nombre VARCHAR(50) NOT NULL, celular VARCHAR(50) NOT NULL, correo VARCHAR(100) NOT NULL);

CREATE TABLE tbl_categoria (ID_Categoria INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(50) NOT NULL, foto VARCHAR(500) NOT NULL, descripcion VARCHAR(1000) NOT NULL);

CREATE TABLE tbl_admin (user VARCHAR(50) NOT NULL PRIMARY KEY, password VARCHAR(50) NOT NULL);
